### ISSUE TITLE
Only One Voice clip gets volume boosted

### ISSUE THREAD

**Issue by MemerOnYT** [Pacil142857/nus3bank-volume-GUI#3]
I've done a few mods for Super Smash Bros. Ultimate, however the past few mods have had low volume on their voices, except for one voice clip. It would always be a random one, from a taunt to a Tilt Attack. How can I fix this, if possible?

**Comment by Pacil142857** [comment]
You're probably not putting anything in the "entry" field. If you leave the field blank, the program will only change the volume of entry #0. Every other entry will retain the same (i.e., low) volume. To fix this, you can edit each entry one-by-one or identify the entries with a low volume and only change those entries.

**Comment by MemerOnYT** [comment]
Wow, I'm shocked I haven't noticed this sooner. However what's questioning me is I did a Sora mod, Black Mage over him, and used the program without putting an entry level, and it turned each volume up to the same amount. But, your solution worked. Thanks a lot!
